services:
  frontend:
    image: "mizkuzy/multi-client"
    mem_limit: 128m
    hostname: frontend
  backend:
    image: "mizkuzy/multi-server"
    mem_limit: 128m
    hostname: backend
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_HOST=$PG_HOST
      - PG_PORT=$PG_PORT
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DATABASE=$PG_DATABASE
  worker:
    image: "mizkuzy/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "mizkuzy/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"