name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build test image
        run: docker build -t mizkuzy/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true mizkuzy/react-test npm test

      - run: docker build -t mizkuzy/multi-client ./client
      - run: docker build -t mizkuzy/multi-nginx ./nginx
      - run: docker build -t mizkuzy/multi-server ./server
      - run: docker build -t mizkuzy/multi-worker ./worker

      - run: docker push mizkuzy/multi-client
      - run: docker push mizkuzy/multi-nginx
      - run: docker push mizkuzy/multi-server
      - run: docker push mizkuzy/multi-worker
